### ISSUE TITLE
Generating a Schema for neoconverse

### ISSUE THREAD

**Issue by nickknyc** [neo4j-labs/neoconverse#6]
How to generate a schema for neoconverse: 
posted here - https://www.linkedin.com/posts/katsivelos_github-neo4j-labsneoconverse-a-genai-activity-7238589751816048640-ttZZ
and here https://s13.nyc/2024/09/08/neoconverse/

I took a screen shot of the setup process video and then fed that into gpt-4o and this prompt "how can i generate a schema like this from a neo4j database"  It worked perfectly.

To generate a schema similar to the one in the image from a Neo4j database, where nodes, properties, and relationships are displayed in a structured format, you can follow these steps:

### 1. **Query for Node Labels and Their Properties**
You can use Cypher queries to extract node labels and properties.

To list all node labels and their properties:

```cypher
MATCH (n)
WITH DISTINCT labels(n) AS labels, keys(n) AS properties
UNWIND labels AS label
RETURN label, collect(DISTINCT properties) AS properties;
```

This will give you a list of node labels and their respective properties.

### 2. **Query for Relationship Types**
To get all relationship types and their properties:

```cypher
MATCH ()-[r]->()
RETURN type(r) AS relationship, keys(r) AS properties
```

This query will return all relationship types and the properties associated with them.

### 3. **Query for Specific Relationship Paths**
To extract the types of relationships between nodes, use the following query:

```cypher
MATCH (a)-[r]->(b)
RETURN DISTINCT labels(a), type(r), labels(b);
```

This will give you a list of unique relationship paths between different node labels.

### 4. **Formatting the Output**
Once you have the data from these queries, you can programmatically format the output in a style similar to what you've shown in the image.

For example, using Python, you can run these Cypher queries and format the result into a readable schema format.

```python
from neo4j import GraphDatabase

def generate_schema(driver):
    schema = {}
    
    # Get Node Labels and Properties
    with driver.session() as session:
        node_data = session.run("MATCH (n) WITH DISTINCT labels(n) AS labels, keys(n) AS properties UNWIND labels AS label RETURN label, collect(DISTINCT properties) AS properties")
        for record in node_data:
            schema[record['label']] = record['properties']
    
    # Get Relationship Types
    relationships = {}
    with driver.session() as session:
        rel_data = session.run("MATCH ()-[r]->() RETURN type(r) AS relationship, keys(r) AS properties")
        for record in rel_data:
            relationships[record['relationship']] = record['properties']

    # Get Paths
    paths = []
    with driver.session() as session:
        path_data = session.run("MATCH (a)-[r]->(b) RETURN DISTINCT labels(a), type(r), labels(b)")
        for record in path_data:
            paths.append(f"({record['labels(a)']})-[:{record['type(r)']}]->({record['labels(b)']})")
    
    return schema, relationships, paths

# Example usage
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))
schema, relationships, paths = generate_schema(driver)
print(schema)
print(relationships)
print(paths)
```

### 5. **Manually Format to Match the Display**
After running these queries and collecting the information, you can format it manually (or programmatically) in a format similar to the example in the image, with node labels and their properties first, followed by the relationships and paths.

This approach will give you a schema visualization that describes the nodes, relationships, and their properties. You can then further enhance it into a format similar to the image you uploaded, either using text or visualization libraries in Python, JavaScript, or any other tool.

**Comment by kumarss20** [comment]
Great work @nickknyc! I appreciate your effort and sharing it here. I'm currently working on the automatic schema generation part and I haven't explicitly documented it yet, but I thought I'd share the schema generation part until the automatic generation part is released.

The steps you outlined to generate schema works perfectly. Here is another schema format that also works:
```
CALL apoc.meta.stats() YIELD relTypes 
WITH  KEYS(relTypes) as relTypes 
UNWIND relTypes as rel
WITH rel, split(split(rel, '[:')[1],']') as relationship
WITH rel, relationship[0] as relationship
CALL apoc.cypher.run("MATCH p = " + rel + " RETURN p LIMIT 10", {})
YIELD value
WITH relationship as relationshipType, nodes(value.p) as nodes, apoc.any.properties(nodes(value.p)[0]) as startNodeProps, apoc.any.properties(nodes(value.p)[-1]) as endNodeProps
WITH DISTINCT labels(nodes[0]) as startNodeLabels, relationshipType, labels(nodes[-1]) as endNodeLabels,  KEYS(startNodeProps) as startNodeProps,  KEYS(endNodeProps) as endNodeProps
WITH startNodeLabels, relationshipType, endNodeLabels, COLLECT(endNodeProps) as endNodeProps, COLLECT(startNodeProps) as startNodeProps
WITH startNodeLabels, relationshipType, endNodeLabels, apoc.coll.toSet(apoc.coll.flatten(endNodeProps)) as endNodeProps, apoc.coll.toSet(apoc.coll.flatten(startNodeProps)) as startNodeProps
RETURN COLLECT({source:{label:startNodeLabels , properties:startNodeProps}, relationship:relationshipType, target:{label:endNodeLabels , properties:endNodeProps}}) as schema
```

I have been incorporating it along with additional features in another branch 

https://github.com/neo4j-labs/neoconverse/blob/func_calling/lib/cypherQuery.ts

**Comment by morawskiPaul** [comment]
Hey @kumarss20 --

This discussion leads to a question that's been on my mind:  Is there a preferred and reliable format for conveying a Neo4j graph schema to an LLM?  The reason I ask is because even within the Neo4j web offerings I see varying formats.  For example, in the GraphAcademy "Build a Neo4j-backed Chatbot using Python" the author uses the internal LangChain code to generate the schema and the result looks something like this:

Node properties are the following:

Movie {title: STRING, tagline: STRING, released: INTEGER},
Person {born: INTEGER, name: STRING}

Relationship properties are the following:

ACTED_IN {roles: LIST},
REVIEWED {summary: STRING, rating: INTEGER}

The relationships are the following:

(:Person)-[:ACTED_IN]->(:Movie),
(:Person)-[:WROTE]->(:Movie),
(:Person)-[:DIRECTED]->(:Movie),
(:Person)-[:PRODUCED]->(:Movie),
(:Person)-[:FOLLOWS]->(:Person),
(:Person)-[:REVIEWED]->(:Movie)

 But if you look at the example in NeoConverse you find a very different format:

Node Labels and Properties with type

['Movie'] : [['title', 'STRING'], ['tagline', 'STRING'], ['released', 'INTEGER']]
['Person'] : [['born', 'INTEGER'], ['name', 'STRING']]

Accepted Relationship paths or patterns

"(:Person)-[:ACTED_IN]->(:Movie)"
"(:Person)-[:WROTE]->(:Movie)"
"(:Person)-[:DIRECTED]->(:Movie)"
"(:Person)-[:PRODUCED]->(:Movie)"
"(:Person)-[:FOLLOWS]->(:Person)"
"(:Person)-[:REVIEWED]->(:Movie)"

Is one of these preferred?  Has anyone experimented to discover the "right" format?

Please comment!

Thanks,

Paul

**Comment by kumarss20** [comment]
Hi @morawskiPaul,

From my experiments, I’ve found that the JSON format of the schema generates Cypher queries slightly more effectively than the other two formats you mentioned. You can extract this JSON format using the Cypher query I shared on this thread around September 12.

It might be beneficial to go beyond a simple text2cypher approach for production applications. While text2cypher works well for simple, exploratory queries, enterprise level applications often require more complex queries with custom logic. Handling all logic within prompt engineering and in-context learning with few-shot examples isn’t optimal for this—an agentic architecture would be more effective.

**Comment by morawskiPaul** [comment]
Hello @kumarss20 --

Thanks for your reply.  Let me ask one question about your schema generation code.

It appears to me that you use apoc.meta.stats to find all "species" of relationship types.  Then, you sample 10 examples
of each species to harvest the node properties.  That may be OK for small graphs, but in my work, each relationship
species has (literally) millions of instances, and the individual nodes don't always contain all of the possible properties.  Even in the simple movies DB I'm playing with, by coincidence, the Persons who REVIEWED Movies have "name" properties
but never have "born" properties, which causes your generated JSON to imply that there are two types of Person --
those with "born" and those without "born".

Is this behavior of your code intentional?  It makes me wonder whether this (possibly unintentional) inconsistency might lead the LLM astray?

Thanks for your thoughts,

Paul
